#!/bin/bash
set -Eexuo pipefail

cd "$(dirname "$0")"/../../.. || exit

APP_ENV=preprod APP_LIVE=a terraform/app/pipeline/format-check
APP_ENV=preprod APP_LIVE=a terraform/app/common-front/format-check
APP_ENV=na APP_LIVE=a terraform/project/format-check
