defaults:
  local: ../package-defaults.yaml

name: dependency-fetcher
version: 0.1.0.0
github: "githubuser/dependency-fetcher"
license: OtherLicense
author: "Author name here"
maintainer: "example@example.com"
copyright: "2019 Author name here"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/dependency-fetcher#readme>

dependencies:
  - base-noprelude
  - common

library:
  source-dirs: src
  dependencies:
    - servant
    - servant-server
    - fused-effects
    - fused-effects-random
    - fused-effects-th
    - random
    - wai
    - warp
    - gogol
    - gogol-pubsub
    - aeson
    - req
    - vector
    - http-client
    - http-types
    - versions
    - containers
    - unordered-containers
    - mtl
    - Cabal
    - hexml
    - hexml-lens
    - modern-uri
    - tagsoup
    - bytestring
    - json-stream
    - text
    - nonempty-vector
    - megaparsec
    - streamly

executables:
  dependency-fetcher-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - dependency-fetcher

tests:
  dependency-fetcher-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - dependency-fetcher
      - common-test

      - fused-effects
      - aeson
      - req
      - vector
      - streamly
      - tagsoup
      - unordered-containers
      - modern-uri
      - nonempty-vector

      - hspec
      - hspec-hedgehog
      - hedgehog

benchmarks:
  package-load:
    source-dirs: bench
    main: Main.hs
    ghc-options:
      - -rtsopts
      - -with-rtsopts=-hm
    dependencies:
      - dependency-fetcher
      - common

      - nonempty-vector
      - vector
      - deepseq
      - weigh
      - streamly
