defaults:
  local: ../package-defaults.yaml

name: front-door
version: 0.1.0.0
github: "githubuser/front-door"
license: OtherLicense
author: "Author name here"
maintainer: "example@example.com"
copyright: "2019 Author name here"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/front-door#readme>

dependencies:
  - base-noprelude
  - common

library:
  source-dirs: src
  dependencies:
    - servant
    - servant-server
    - fused-effects
    - fused-effects-random
    - random
    - github-webhooks
    - servant-github-webhook
    - wai
    - warp
    - gogol
    - aeson
    - nonempty-vector

executables:
  front-door-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - front-door

tests:
  front-door-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - front-door
      - common-test

      - servant-github-webhook
      - github-webhooks
      - vector
      - fused-effects

      - hspec
      - hspec-hedgehog
      - hedgehog
