steps:

  - label: ':mag_right: Determine Live'
    command: .buildkite/commands/set-app-live-meta

  - wait

  - label: ':terraform: Deploy Non Live'
    command: .buildkite/commands/deploy-app

  - wait

  - label: ':terraform: Switch Common Front'
    command: .buildkite/commands/switch-common-front

  - wait

  - label: ':sleeping: Wait For Deploy'
    branches: master
    command: .buildkite/commands/sleep-post-deploy

  - wait

  # doesn't seem to be a good way to execute a step only if the build fails
  - label: ':smoking: Smoke Test + Roll Back'
    command: .buildkite/commands/smoke-test-roll-back
