defaults:
  local: ../package-defaults.yaml

name: common-test
version: 0.1.0.0
github: "githubuser/common-test"
license: OtherLicense
author: "Author name here"
maintainer: "example@example.com"
copyright: "2019 Author name here"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/common-test#readme>

dependencies:
  - base-noprelude

library:
  source-dirs: src
  dependencies:
    - common

    - gogol
    - gogol-pubsub
    - vector
    - nonempty-vector
    - aeson
    - modern-uri

    - hedgehog
    - relude

tests:
  common-test-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - common-test
      - common

      - lens
      - aeson
      - vector
      - nonempty-vector
      - fused-effects
      - base64
      - pretty-simple

      - hspec
      - hspec-hedgehog
