#!/bin/bash
set -Eexuo pipefail

cd "$(dirname "$0")"/.. || exit

ORMOLU_MODE=inplace APPLY_TO="${1:-MODIFIED}" auto/latest-environment \
  stack build \
    --stack-yaml stack-dev-deps.yaml \
    --dependencies-only \
    --exec 'auto/bin/ormolu-exec'
