#!/bin/bash
set -Eexuo pipefail

cd "$(dirname "$0")"/../../.. || exit

auto/dev-environment \
  stack test \
    --no-run-tests \
    --ghc-options '-fwrite-ide-info' \
    --exec 'weeder --config ./apps/weeder.dhall'
